version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on: ["redis", "minio"]

  worker:
    build: ./worker
    env_file: ./worker/.env
    depends_on: ["redis", "minio"]

  zipper:
    build: ./zipper
    env_file: ./zipper/.env
    depends_on: ["redis", "minio"]

volumes:
  minio-data:
